STOP_WORDS: set[str] = {
    # prepositions
    "на",
    "у",
    "в",
    "для",
    "за",
    "з",
    "із",
    "зі",
    "до",
    "від",
    "по",
    "про",
    "при",
    "над",
    "під",
    "між",
    "через",
    "без",
    "біля",
    "перед",
    "після",
    "замість",
    # conjunctions
    "і",
    "та",
    "але",
    "або",
    "чи",
    "що",
    "як",
    "коли",
    "якщо",
    "бо",
    "тому",
    "тоді",
    "хоча",
    # pronouns
    "я",
    "ти",
    "він",
    "вона",
    "воно",
    "ми",
    "ви",
    "вони",
    "мій",
    "твій",
    "його",
    "її",
    "наш",
    "ваш",
    "їх",
    "це",
    "той",
    "ті",
    "цей",
    "ця",
    "ці",
    # particles & common words
    "не",
    "ні",
    "так",
    "вже",
    "ще",
    "теж",
    "також",
    "де",
    "там",
    "тут",
}

DEFAULT_CATEGORIES: list[dict] = [
    {
        "name": "Їжа",
        "emoji": "🍔",
        "system_code": "food",
        "keywords": [
            "кава",
            "обід",
            "вечеря",
            "сніданок",
            "ресторан",
            "кафе",
            "продукти",
            "їжа",
            "піца",
            "бургер",
        ],
    },
    {
        "name": "Транспорт",
        "emoji": "🚇",
        "system_code": "transport",
        "keywords": [
            "таксі",
            "метро",
            "автобус",
            "бензин",
            "паливо",
            "проїзд",
            "uber",
            "bolt",
            "uklon",
        ],
    },
    {
        "name": "Комунальні",
        "emoji": "🏠",
        "system_code": "utilities",
        "keywords": [
            "світло",
            "газ",
            "вода",
            "інтернет",
            "оренда",
            "квартира",
            "комуналка",
        ],
    },
    {
        "name": "Розваги",
        "emoji": "🎮",
        "system_code": "entertainment",
        "keywords": ["кіно", "гра", "концерт", "бар", "клуб", "steam", "playstation"],
    },
    {
        "name": "Підписки",
        "emoji": "💳",
        "system_code": "subscriptions",
        "keywords": [
            "claude",
            "chatgpt",
            "youtube",
            "netflix",
            "spotify",
            "apple",
            "icloud",
            "google",
            "github",
            "jetbrains",
            "підписка",
        ],
    },
    {
        "name": "Покупки",
        "emoji": "🛒",
        "system_code": "shopping",
        "keywords": ["одяг", "взуття", "техніка", "магазин", "amazon", "rozetka"],
    },
    {
        "name": "Здоров'я",
        "emoji": "💊",
        "system_code": "health",
        "keywords": ["аптека", "ліки", "лікар", "спортзал", "вітаміни", "стоматолог"],
    },
    {
        "name": "Освіта",
        "emoji": "📚",
        "system_code": "education",
        "keywords": ["книга", "курс", "udemy", "coursera", "навчання"],
    },
    {
        "name": "Інше",
        "emoji": "❓",
        "system_code": "other",
        "keywords": [],
    },
]
