DEFAULT_CATEGORIES: list[dict] = [
    {
        "name": "Їжа",
        "emoji": "🍔",
        "system_code": "food",
        "keywords": [
            "кава",
            "обід",
            "вечеря",
            "сніданок",
            "ресторан",
            "кафе",
            "продукти",
            "їжа",
            "піца",
            "бургер",
        ],
    },
    {
        "name": "Транспорт",
        "emoji": "🚇",
        "system_code": "transport",
        "keywords": [
            "таксі",
            "метро",
            "автобус",
            "бензин",
            "паливо",
            "проїзд",
            "uber",
            "bolt",
            "uklon",
        ],
    },
    {
        "name": "Комунальні",
        "emoji": "🏠",
        "system_code": "utilities",
        "keywords": [
            "світло",
            "газ",
            "вода",
            "інтернет",
            "оренда",
            "квартира",
            "комуналка",
        ],
    },
    {
        "name": "Розваги",
        "emoji": "🎮",
        "system_code": "entertainment",
        "keywords": ["кіно", "гра", "концерт", "бар", "клуб", "steam", "playstation"],
    },
    {
        "name": "Підписки",
        "emoji": "💳",
        "system_code": "subscriptions",
        "keywords": [
            "claude",
            "chatgpt",
            "youtube",
            "netflix",
            "spotify",
            "apple",
            "icloud",
            "google",
            "github",
            "jetbrains",
            "підписка",
        ],
    },
    {
        "name": "Покупки",
        "emoji": "🛒",
        "system_code": "shopping",
        "keywords": ["одяг", "взуття", "техніка", "магазин", "amazon", "rozetka"],
    },
    {
        "name": "Здоров'я",
        "emoji": "💊",
        "system_code": "health",
        "keywords": ["аптека", "ліки", "лікар", "спортзал", "вітаміни", "стоматолог"],
    },
    {
        "name": "Освіта",
        "emoji": "📚",
        "system_code": "education",
        "keywords": ["книга", "курс", "udemy", "coursera", "навчання"],
    },
    {
        "name": "Інше",
        "emoji": "❓",
        "system_code": "other",
        "keywords": [],
    },
]
